// Mock transaction data
export const mockTransactions = [
    {
        id: '1',
        amount: 500,
        merchant: 'Starbucks',
        category: 'Food & Dining',
        date: new Date('2025-11-25T09:30:00'),
        type: 'debit',
        isLeak: true,
        leakSeverity: 'medium',
        leakReason: 'Frequent small purchases',
    },
    {
        id: '2',
        amount: 1200,
        merchant: 'Netflix',
        category: 'Subscriptions',
        date: new Date('2025-11-24T00:00:00'),
        type: 'debit',
        isLeak: true,
        leakSeverity: 'high',
        leakReason: 'Price increased from ₹999 to ₹1200',
    },
    {
        id: '3',
        amount: 350,
        merchant: 'Uber',
        category: 'Transportation',
        date: new Date('2025-11-24T18:45:00'),
        type: 'debit',
        isLeak: false,
    },
    {
        id: '4',
        amount: 150,
        merchant: 'Cafe Coffee Day',
        category: 'Food & Dining',
        date: new Date('2025-11-23T14:20:00'),
        type: 'debit',
        isLeak: true,
        leakSeverity: 'low',
        leakReason: 'Daily coffee expense',
    },
    {
        id: '5',
        amount: 2500,
        merchant: 'Amazon',
        category: 'Shopping',
        date: new Date('2025-11-22T11:00:00'),
        type: 'debit',
        isLeak: false,
    },
    {
        id: '6',
        amount: 799,
        merchant: 'Spotify',
        category: 'Subscriptions',
        date: new Date('2025-11-21T00:00:00'),
        type: 'debit',
        isLeak: false,
    },
    {
        id: '7',
        amount: 450,
        merchant: 'Swiggy',
        category: 'Food & Dining',
        date: new Date('2025-11-20T20:30:00'),
        type: 'debit',
        isLeak: true,
        leakSeverity: 'medium',
        leakReason: 'Frequent food delivery',
    },
    {
        id: '8',
        amount: 5000,
        merchant: 'Salary Credit',
        category: 'Income',
        date: new Date('2025-11-20T09:00:00'),
        type: 'credit',
        isLeak: false,
    },
];

// Mock leak insights
export const mockLeakInsights = [
    {
        id: '1',
        title: 'Coffee Addiction Alert',
        description: 'You\'ve spent ₹2,450 on coffee this month',
        severity: 'medium',
        category: 'Food & Dining',
        savings: 1800,
        alternative: 'Make coffee at home and save ₹1,800/month',
        icon: 'cafe',
    },
    {
        id: '2',
        title: 'Netflix Price Hike',
        description: 'Your subscription increased by ₹201',
        severity: 'high',
        category: 'Subscriptions',
        savings: 201,
        alternative: 'Consider family plan or annual subscription',
        icon: 'tv',
    },
    {
        id: '3',
        title: 'Food Delivery Spree',
        description: '12 food delivery orders this month',
        severity: 'high',
        category: 'Food & Dining',
        savings: 3500,
        alternative: 'Cook at home 3 times a week and save ₹3,500',
        icon: 'fast-food',
    },
    {
        id: '4',
        title: 'Unused Gym Membership',
        description: 'No activity detected in 45 days',
        severity: 'high',
        category: 'Subscriptions',
        savings: 1500,
        alternative: 'Cancel and try home workouts',
        icon: 'fitness',
    },
];

// Mock statistics
export const mockStats = {
    totalSpent: 15450,
    totalLeaks: 5280,
    leaksDetected: 7,
    potentialSavings: 7001,
    safeToSpend: 8720,
    monthlyBudget: 25000,
};

// Mock subscriptions
export const mockSubscriptions = [
    {
        id: '1',
        name: 'Netflix',
        amount: 1200,
        frequency: 'monthly',
        nextBilling: new Date('2025-12-24'),
        status: 'active',
        priceChange: 201,
    },
    {
        id: '2',
        name: 'Spotify',
        amount: 799,
        frequency: 'monthly',
        nextBilling: new Date('2025-12-21'),
        status: 'active',
    },
    {
        id: '3',
        name: 'Amazon Prime',
        amount: 1499,
        frequency: 'yearly',
        nextBilling: new Date('2026-03-15'),
        status: 'active',
    },
    {
        id: '4',
        name: 'Gym Membership',
        amount: 1500,
        frequency: 'monthly',
        nextBilling: new Date('2025-12-01'),
        status: 'inactive',
    },
];
